# Generated by Django 3.2.18 on 2023-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_hardware_type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bms_hardware_type',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
