# Generated by Django 3.2.18 on 2023-04-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '0001_initial'),
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_users_register',
            name='department_id',
            field=models.ManyToManyField(to='Device.Bms_department_master'),
        ),
        migrations.AddField(
            model_name='bms_users_register',
            name='locker_id',
            field=models.ManyToManyField(to='Device.Bms_locker'),
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='department_id',
            field=models.ManyToManyField(related_name='dep', to='Device.Bms_department_master'),
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='locker_id',
            field=models.ManyToManyField(related_name='locker', to='Device.Bms_locker'),
        ),
        migrations.AddField(
            model_name='bms_users',
            name='role_id',
            field=models.ManyToManyField(blank=True, related_name='song', to='Authenticate.Bms_Roles'),
        ),
        migrations.AddField(
            model_name='bms_users',
            name='user_details',
            field=models.ManyToManyField(related_name='abc', to='Authenticate.Bms_Users_Details'),
        ),
        migrations.AddField(
            model_name='bms_user_type',
            name='type_name',
            field=models.ManyToManyField(blank=True, related_name='aaa', to='Authenticate.Bms_Roles'),
        ),
        migrations.AddField(
            model_name='bms_roles',
            name='permissions_id',
            field=models.ManyToManyField(related_name='dev', to='Authenticate.Bms_Module_master'),
        ),
    ]
